esphome:
  name: cam
  friendly_name: Cam

esp32:
  board: esp32cam
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret cam_key

ota:
  password: !secret cam_ota

web_server:
  port: 80
  include_internal: true  # Allows internal components like camera stream

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cam Fallback Hotspot"
    password: !secret cam_hotspot

captive_portal:
    
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  
  name: My ESP32-CAM 
  
  resolution: 640x480  # Lower if performance is bad
  jpeg_quality: 10     # Lower for better quality, higher for lower bandwidth
  max_framerate: 15fps
  idle_framerate: 1fps  # Save resources when not streaming
  vertical_flip: false     # Set to true if the image is upside down
  horizontal_mirror: false # Set to true if needed



output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    name: flashlight